usr/bin/idasen-companion
usr/bin/idasen-companiond
usr/lib/python3*/dist-packages/idasen_companion/
usr/lib/python3*/dist-packages/idasen_companion-*.dist-info/
data/io.github.extricator.IdasenCompanion.desktop usr/share/applications/
data/icons/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/scalable/apps/
data/icons/io.github.extricator.IdasenCompanion-symbolic.svg usr/share/icons/hicolor/scalable/apps/
data/icons/hicolor/128x128/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/128x128/apps/
data/icons/hicolor/16x16/status/io.github.extricator.IdasenCompanion-symbolic.svg usr/share/icons/hicolor/16x16/status/
data/icons/hicolor/16x16@2/status/io.github.extricator.IdasenCompanion-symbolic.svg usr/share/icons/hicolor/16x16@2/status/
data/icons/hicolor/16x16/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/16x16/apps/
data/icons/hicolor/22x22/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/22x22/apps/
data/icons/hicolor/22x22/status/io.github.extricator.IdasenCompanion-symbolic.svg usr/share/icons/hicolor/22x22/status/
data/icons/hicolor/22x22@2/status/io.github.extricator.IdasenCompanion-symbolic.svg usr/share/icons/hicolor/22x22@2/status/
data/icons/hicolor/24x24/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/24x24/apps/
data/icons/hicolor/256x256/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/256x256/apps/
data/icons/hicolor/32x32/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/32x32/apps/
data/icons/hicolor/48x48/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/48x48/apps/
data/icons/hicolor/64x64/apps/io.github.extricator.IdasenCompanion.svg usr/share/icons/hicolor/64x64/apps/
data/io.github.extricator.IdasenCompanion.metainfo.xml usr/share/metainfo/
