#!/usr/bin/env bash
# Build the sdist and wheel, and refuse to produce either if it contains
# something nobody meant to ship.
#
# MANIFEST.in reads the *filesystem*, not git — that is how the sdist once
# published an untracked design-tool export whose screenshots were ~90% of
# the tarball. This script is the one command, local or CI, that catches
# that class of mistake before an artifact reaches anyone:
#
#   1. Refuse to start if an untracked file sits under a packaged directory.
#   2. Every sdist member must be tracked in git (the root-cause check).
#   3. The sdist must stay under a fixed size ceiling.
#   4. The wheel must contain a compiled catalog for every tracked PO source.
#
# All four gate on exit codes only, never on printed text — a coverage tool
# in this project was found to print "FAIL" and exit 0 at an integer
# boundary, so text is not trustworthy as a pass/fail signal.
set -euo pipefail

cd "$(dirname "$0")/.."

PYTHON=${PYTHON:-python3}

echo ">> Checking for untracked files under packaged directories..."
UNTRACKED=$(git ls-files --others --exclude-standard -- \
    src data packaging docs translations po tests scripts)
if [ -n "$UNTRACKED" ]; then
    echo "error: untracked files sit under a packaged directory:" >&2
    echo "$UNTRACKED" >&2
    exit 1
fi

echo ">> Clearing stale build metadata..."
rm -rf src/*.egg-info dist

echo ">> Building sdist and wheel..."
"$PYTHON" -m build

SDIST=$(ls dist/*.tar.gz)
WHEEL=$(ls dist/*.whl)

echo ">> Checking every sdist member is tracked in git..."
MEMBER_COUNT=$("$PYTHON" - "$SDIST" <<'PYEOF'
import fnmatch
import subprocess
import sys
import tarfile

tarpath = sys.argv[1]

# Generated by setuptools at build time, never tracked in git. Anything
# else in the sdist must be a real, reviewed, tracked file.
allow_exact = {"PKG-INFO", "setup.cfg"}
egg_info_pattern = "src/*.egg-info/*"

tracked = set(
    subprocess.run(
        ["git", "ls-files"], capture_output=True, text=True, check=True
    ).stdout.splitlines()
)

with tarfile.open(tarpath) as tar:
    members = tar.getmembers()

offenders = []
file_count = 0
for member in members:
    if member.isdir():
        continue
    # Every member is wrapped in a leading "<name>-<version>/" directory;
    # strip it before comparing against git's paths.
    _, _, rel = member.name.partition("/")
    if not rel:
        continue
    file_count += 1
    if rel in allow_exact:
        continue
    if fnmatch.fnmatch(rel, egg_info_pattern):
        continue
    if rel not in tracked:
        offenders.append(rel)

if offenders:
    print("error: sdist contains untracked members:", file=sys.stderr)
    for path in offenders:
        print(f"  {path}", file=sys.stderr)
    sys.exit(1)

print(file_count)
PYEOF
)

echo ">> Checking the sdist stays under the size ceiling..."
SDIST_SIZE=$("$PYTHON" -c "import os,sys;print(os.path.getsize(sys.argv[1]))" "$SDIST")
# 850000 bytes: just above the ~821 kB sdist measured after the five-artifact
# release scripts, generated Flatpak dependency lock and Debian flavor
# manifests became required packaged-test inputs. Still far below either
# accident this guards against -- an untracked design-tool export once added
# ~1.1 MB, and the screenshot directory would add ~650 kB on its own.
SDIST_SIZE_CEILING=850000
if [ "$SDIST_SIZE" -gt "$SDIST_SIZE_CEILING" ]; then
    echo "error: sdist is ${SDIST_SIZE} bytes, over the ${SDIST_SIZE_CEILING}-byte ceiling" >&2
    exit 1
fi

echo ">> Checking the wheel contains the compiled app catalogs..."
"$PYTHON" - "$WHEEL" <<'PYEOF'
from pathlib import Path
import subprocess
import sys
import zipfile

wheelpath = sys.argv[1]

# Wheel contents come from [tool.setuptools.package-data] in pyproject.toml,
# not MANIFEST.in, so the risk here inverts: shipping too little rather
# than too much. A missing catalog is a silently untranslated app.
mo_pattern = "idasen_companion/locale/*/LC_MESSAGES/idasen_companion.mo"

with zipfile.ZipFile(wheelpath) as wheel:
    names = set(wheel.namelist())

catalogs = subprocess.run(
    ["git", "ls-files", "--", "po/*.po"],
    capture_output=True, text=True, check=True,
).stdout.splitlines()
if not catalogs:
    print("error: no tracked translation sources in po/", file=sys.stderr)
    sys.exit(1)

expected = {mo_pattern.replace("*", Path(catalog).stem) for catalog in catalogs}
missing = sorted(expected - names)

if missing:
    print("error: wheel is missing compiled catalog(s):", file=sys.stderr)
    for path in missing:
        print(f"  {path}", file=sys.stderr)
    sys.exit(1)
PYEOF

echo ">> sdist: ${MEMBER_COUNT} members, ${SDIST_SIZE} bytes — all tracked"
